services:
  app:
    restart: always
    depends_on:
      - db
    build:
      dockerfile: ./app.Dockerfile
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    command:
      - /bin/sh
      - -c
      - |
        npx prisma generate
        npx prisma migrate deploy
        npm run start:dev
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    networks:
      - bridge-network

  db:
    restart: always
    build:
      dockerfile: ./db.Dockerfile
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bridge-network

volumes:
  db-data:
networks:
  bridge-network:
    driver: bridge
